"""pykit-llm — LLM provider abstractions with discriminated union message types."""

from pykit_llm.config import LLMConfig
from pykit_llm.provider import LLMProvider
from pykit_llm.types import (
    AssistantMessage,
    CompletionRequest,
    CompletionResponse,
    ContentBlock,
    FunctionCall,
    ImageBlock,
    Message,
    StopReason,
    StreamChunk,
    SystemMessage,
    TextBlock,
    ThinkingBlock,
    ToolCall,
    ToolChoice,
    ToolResultBlock,
    ToolResultMessage,
    ToolUseBlock,
    Usage,
    UserMessage,
    assistant,
    system,
    text_content,
    text_of,
    tool_result_msg,
    user,
)

__all__ = [
    "AssistantMessage",
    "CompletionRequest",
    "CompletionResponse",
    "ContentBlock",
    "FunctionCall",
    "ImageBlock",
    "LLMConfig",
    "LLMProvider",
    "Message",
    "StopReason",
    "StreamChunk",
    "SystemMessage",
    "TextBlock",
    "ThinkingBlock",
    "ToolCall",
    "ToolChoice",
    "ToolResultBlock",
    "ToolResultMessage",
    "ToolUseBlock",
    "Usage",
    "UserMessage",
    "assistant",
    "system",
    "text_content",
    "text_of",
    "tool_result_msg",
    "user",
]
