"""pykit-agent — Agent loop with tool execution, hooks, and context management."""

from pykit_agent.agent import Agent, AgentConfig
from pykit_agent.command import Command, CommandRegistry, register_builtins
from pykit_agent.hooks import (
    EVENT_ON_ERROR,
    EVENT_POST_LLM_CALL,
    EVENT_POST_TOOL_CALL,
    EVENT_PRE_LLM_CALL,
    EVENT_PRE_TOOL_CALL,
    EVENT_TURN_END,
    EVENT_TURN_START,
    OnError,
    PostLLMCall,
    PostToolCall,
    PreLLMCall,
    PreToolCall,
    TurnEnd,
    TurnStart,
)
from pykit_agent.memory import InMemoryStore, Memory, SlidingWindowMemory
from pykit_agent.prompt import PromptBuilder, PromptTemplate
from pykit_agent.types import (
    AgentEvent,
    AgentResult,
    CompleteEvent,
    ContextCompactedEvent,
    ContextExceededError,
    ContextStrategy,
    FailStrategy,
    StopReason,
    ToolCompleteEvent,
    ToolExecutingEvent,
    TruncateStrategy,
    TurnCompleteEvent,
    TurnStartEvent,
)

__all__ = [
    "EVENT_ON_ERROR",
    "EVENT_POST_LLM_CALL",
    "EVENT_POST_TOOL_CALL",
    "EVENT_PRE_LLM_CALL",
    "EVENT_PRE_TOOL_CALL",
    "EVENT_TURN_END",
    "EVENT_TURN_START",
    "Agent",
    "AgentConfig",
    "AgentEvent",
    "AgentResult",
    "Command",
    "CommandRegistry",
    "CompleteEvent",
    "ContextCompactedEvent",
    "ContextExceededError",
    "ContextStrategy",
    "FailStrategy",
    "InMemoryStore",
    "Memory",
    "OnError",
    "PostLLMCall",
    "PostToolCall",
    "PreLLMCall",
    "PreToolCall",
    "PromptBuilder",
    "PromptTemplate",
    "SlidingWindowMemory",
    "StopReason",
    "ToolCompleteEvent",
    "ToolExecutingEvent",
    "TruncateStrategy",
    "TurnCompleteEvent",
    "TurnEnd",
    "TurnStart",
    "TurnStartEvent",
    "register_builtins",
]
