"""Composable git repository interfaces with embedded and CLI backends."""

from pykit_git.auth import BasicAuth, GPGSigningKey, SSHKey, SSHSigningKey, Token, TokenProvider
from pykit_git.core import Executor, Repository
from pykit_git.manage import ConfigReader, Maintainer, RefManager, RemoteManager
from pykit_git.options import (
    BlameOptions,
    CheckoutOptions,
    CherryPickOptions,
    CleanOptions,
    CommitOptions,
    DescribeOptions,
    ExtraArgs,
    FetchOptions,
    GrepOptions,
    LogOptions,
    MergeOptions,
    PushOptions,
    RebaseOptions,
)
from pykit_git.read import Blamer, Differ, Inspector, LogReader, TreeReader
from pykit_git.repo import Repo, clone, discover, init, init_bare, open_repo
from pykit_git.types import (
    BlameLine,
    Branch,
    BranchFilter,
    Commit,
    DiffEntry,
    DiffStats,
    EntryKind,
    EntryState,
    FileStatus,
    GrepMatch,
    MergeResult,
    Oid,
    RebaseResult,
    Reference,
    Remote,
    ResetMode,
    Signature,
    StashEntry,
    StatusEntry,
    Tag,
    TreeEntry,
    TreeHash,
)
from pykit_git.write import Checker, CherryPicker, Committer, IndexManager, Merger, Rebaser, Resetter, Stasher

__all__ = [
    "BasicAuth",
    "BlameLine",
    "BlameOptions",
    "Blamer",
    "Branch",
    "BranchFilter",
    "Checker",
    "CherryPickOptions",
    "CherryPicker",
    "CheckoutOptions",
    "CleanOptions",
    "Commit",
    "CommitOptions",
    "Committer",
    "ConfigReader",
    "DescribeOptions",
    "Differ",
    "DiffEntry",
    "DiffStats",
    "EntryKind",
    "EntryState",
    "Executor",
    "ExtraArgs",
    "FetchOptions",
    "FileStatus",
    "GPGSigningKey",
    "GrepMatch",
    "GrepOptions",
    "IndexManager",
    "Inspector",
    "init",
    "init_bare",
    "LogOptions",
    "LogReader",
    "Maintainer",
    "MergeOptions",
    "Merger",
    "MergeResult",
    "Oid",
    "PushOptions",
    "RebaseOptions",
    "Rebaser",
    "RebaseResult",
    "Reference",
    "Remote",
    "RemoteManager",
    "Repo",
    "Repository",
    "ResetMode",
    "Resetter",
    "RefManager",
    "SSHKey",
    "SSHSigningKey",
    "Signature",
    "Stasher",
    "StashEntry",
    "StatusEntry",
    "Tag",
    "Token",
    "TokenProvider",
    "TreeEntry",
    "TreeHash",
    "TreeReader",
    "clone",
    "discover",
    "open_repo",
]
